name: Generate and Publish Docs

on:
    push:
        branches:
            - main

jobs:
    build-docs:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.x

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pypandoc

          - name: Convert Markdown to reStructuredText
            run: |
                for file in $(find . -name "*.md"); do
                    pypandoc "$file" -f markdown -t rst -o "${file%.md}.rst"
                done

          - name: Upload converted files
            uses: actions/upload-artifact@v2
            with:
                name: converted-docs
                path: '**/*.rst'
